### ISSUE TITLE
当日やること会議場

### ISSUE THREAD

**Issue by utgwkk** [utgwkk/isucon9q#1]
# 競技始まったらやること
- [x] みんなの公開鍵を配置する
  - [x] ssh config 共有する
- [x] レギュレーション把握する http://isucon.net/archives/53555007.html
- [x] 当日マニュアル読む https://gist.github.com/sota1235/a7356a5909af264c1c1c840dd216c98f
   - [x] 得点源列挙する
   - [x] webapp/docs 以下を読む
- [x] アプリケーションの雰囲気をつかむ
- [ ] サーバに入ってるソフトウェア・ミドルウェアを把握する
- [x] 初期実装でベンチ回す
- [x] 計測する
- [ ] N+1潰す
- [ ] リソースについて共通かユーザ固有かをしらべる
  - [ ] 共通リソースにはキャッシュが効く
- [x] DBスキーマはく
  - [ ] 知らない機能を殺す

他にあったらてきとうに追記してください

**Comment by nonylene** [comment]
https://github.com/matsuu/kataribe 入れた
```
kataribe -generate
cat /var/log/nginx/access.log | kataribe
```
